/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Please enter the game number and press Enter.");
        System.out.println("1 - Great");
        System.out.println("2 - Even");
        System.out.println("3 - Calc");
        System.out.println("4 - GSD");
        System.out.println("0 - Exit");
        System.out.print("Your choice: ");
        if (scanner.hasNextInt()) {
            int numOfGame = scanner.nextInt();
            if (0 < numOfGame && numOfGame <= 4) {
                Engine.start(numOfGame);
            }
        }
        scanner.close();
    }
}
